# PyTorch : Fonctions utiles
Nicolas Baskiotis (nicolas.baskiotis@lip6.fr)

# Préambule

Les lignes suivantes permettent d'importer pytorch et vérifier qu'un GPU est disponible.

In [1]:
import torch
print("La version de torch est : ",torch.__version__)
print("Le calcul GPU est disponible ? ", torch.cuda.is_available())

import numpy as np
import sklearn

La version de torch est :  1.8.1+cu102
Le calcul GPU est disponible ?  True


# Prise en main de Pytorch

Cette partie est un tutoriel pour la prise en main de pytorch. N'hesitez pas à explorer et expérimenter les notions présentées.

## Syntaxe

Le principal objet manipulé sous Pytorch est **torch.Tensor** qui correspond à un tenseur mathématique (généralisation de la notion de matrice en $n$-dimensions), très proche dans l'utilisation de **numpy.array**.   Cet objet est optimisé pour les calculs sur GPU ce qui implique quelques contraintes plus importantes que sous **numpy**. En particulier :
* le type du tenseur manipulé est très important et les conversions ne sont pas automatique (**FloatTensor** de type **torch.float**, **DoubleTensor** de type **torch.double**,  **ByteTensor** de type **torch.byte**, **IntTensor** de type **torch.int**, **LongTensor** de type **torch.long**). Pour un tenseur **t** La conversion se fait très simplement en utilisant les fonctions : **t.double()**, **t.float()**, **t.long()** ...
* la plupart des opérations ont une version *inplace*, c'est-à-dire qui modifie le tenseur plutôt que de renvoyer un nouveau tenseur; elles sont suffixées par **_** (**add_** par exemple).

Voici ci-dessous quelques exemples d'opérations usuelles, n'hésitez pas à vous référez à la [documentation officielle](https://pytorch.org/docs/stable/tensors.html) pour la liste exhaustive des opérations.


In [2]:
# Création de tenseurs et caractéristiques
## Créer un tenseur à partir d'une liste
print(torch.tensor([[1.,2.,3.],[2.,3,4.]])) 
## Créer un tenseur  tenseur rempli de 1 de taille 2x3x4
print(torch.ones(2,3,4)) 
## tenseur de zéros de taille 2x3 de type float
print(torch.zeros(2,3,dtype=torch.float))  
## tirage uniforme entier entre 10 et 15, 
## remarquez l'utilisation du _ dans random pour l'opération inplace
print(torch.zeros(2,3).random_(10,15)) 
## tirage suivant la loi normale
a=torch.zeros(2,3).normal_(1,0.1)
print(a)
## equivalent à zeros(3,4).normal_
b = torch.randn(3,4) 
## Création d'un vecteur
c = torch.randn(3)
## concatenation de tenseurs
print(torch.cat((a,a),1))
## Taille des tenseurs/vecteurs
print(a.size(1),b.shape,c.size())
## Conversion de type
print(a.int(),a.int().type())

# Opérations élémentaires sur les tenseurs
## produit scalaire (et contrairement à numpy, que produit scalaire)
print(c.dot(c))
## produit matriciel : utilisation de @ ou de la fonction mm
print(a.mm(b), a @ b)
## transposé
print(a.t(),a.T)
## index du maximum selon une dimension
print("argmax : ",a.argmax(dim=1))
## somme selon une dimension/de tous les éléments
print(b.sum(1), b.sum()) 
## moyenne selon  une dimension/sur tous les éléments
print(b.mean(1), b.mean())
## changer la taille du tenseur (la taille totale doit être inchangée)
print(b.view(2,6))
## somme/produit/puissance termes a termes
print(a+a,a*a,a**2)
## attention ! comme sous numpy, il peut y avoir des pièges ! 
## Vérifier toujours les dimensions !!
a=torch.zeros(5,1)
b=torch.zeros(5)
## la première opération fait un broadcast et le résultat est tenseur à 2 dimensiosn,
## le résultat de la deuxième opération est bien un vecteur
print(a-b,a.t()-b)

tensor([[1., 2., 3.],
        [2., 3., 4.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[14., 11., 14.],
        [12., 14., 11.]])
tensor([[0.8637, 1.1015, 1.0611],
        [1.0797, 1.0414, 1.0447]])
tensor([[0.8637, 1.1015, 1.0611, 0.8637, 1.1015, 1.0611],
        [1.0797, 1.0414, 1.0447, 1.0797, 1.0414, 1.0447]])
3 torch.Size([3, 4]) torch.Size([3])
tensor([[0, 1, 1],
        [1, 1, 1]], dtype=torch.int32) torch.IntTensor
tensor(1.3262)
tensor([[-0.6620, -1.8156,  3.3477,  0.4739],
        [-0.6093, -1.7406,  3.2896,  0.2775]]) tensor([[-0.6620, -1.8156,  3.3477,  0.4739],
        [-0.6093, -1.7406,  3.2896,  0.2775]])
tensor([[0.8637, 1.0797],
        [1.1015, 1.0414],
        [1.0611, 1.0447]]) tensor([[0.8637, 1.0797],
        [1.1015, 1.0414],
        [1.0611, 1.0447]])
argmax :  tensor([1, 0])
tensor([ 0.0